### PR TITLE
Upgrade packages versions

### LINKED ISSUE #4: Old versions of packages
Some of the dependencies (python packages) have a old version (for example, `pydantic`).  For this reason, it is difficult to use this `ankr-sdk` in a modern python stack or new python apps.

For example:

```sh
# create new conda env
conda create -n web3_demo python=3.11
conda activate web3_demo 

# it's just a typical data science app package list with ankr-sdk
cat requirements.txt 

> # data models
> pydantic>=2.6.1,<2.7
> pydantic-settings>=2.1.0,<2.2
> # data processing
> pandas>=2.2.0,<2.3
> pyarrow>=15.0.0,<15.1
> pandera>=0.18.0,<0.19
> # network and web
> httpx>=0.26.0,<0.27
> backoff>=2.2.1,<2.3
> fastapi>=0.109.2,<0.110
> # numerics and finance
> numpy>=1.26.4,<1.27
> scipy>=1.12.0,<1.13
> # blockchain
> web3>=6.15.1,<6.16
> ankr-sdk>=1.0.0,<1.1   # <---- Ankr SDK
> # others
> PyYAML>=6.0.1,<6.1

pip install -U -r requirements.txt 

> ERROR: Cannot install -r requirements.txt (line 11), -r requirements.txt (line 17), -r requirements.txt (line 3), -r requirements.txt (line 7) and pydantic<2.7 and >=2.6.1 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     The user requested pydantic<2.7 and >=2.6.1
>     pydantic-settings 2.1.0 depends on pydantic>=2.3.0
>     pandera 0.18.0 depends on pydantic
>     fastapi 0.109.2 depends on pydantic!=1.8, !=1.8.1, !=2.0.0, !=2.0.1, !=2.1.0, <3.0.0 and >=1.7.4
>     ankr-sdk 1.0.0 depends on pydantic<2.0.0 and >=1.10.8
```

### PR DESCRIPTION
**Pull request by codez0mb1e**
Changelog:

- Upgrade packages versions #4  
- Remove `poetry.lock` as [redundant for package distribution](https://python-poetry.org/docs/basic-usage/#as-a-library-developer).

### CODE REVIEW

**Comment by RedCuckoo** [comment]
Hello, thank you for the issue and pull request. Please, comment here when it will be ready for review.

**Comment by codez0mb1e** [comment]
> Hello, thank you for the issue and pull request. Please, comment here when it will be ready for review.

Hello, Yurii @RedCuckoo. It's ready for review.

**Review by RedCuckoo — APPROVED** [review]

**Comment by RedCuckoo** [comment]
I will update here, when the version will be released, some fixes have to be done.

**Comment by RedCuckoo** [comment]
@codez0mb1e thank you for the contribution again and sorry it took so long to deliver. New version v1.0.1 is available and has been released

**Pull request merged**
